// $.getClientInfo(function (res) {
//         _buy_main_ip = res.ip;
//         _buy_main_userAgent = res.userAgent;
//     });

var a = 'jtDcjtiYx1nsvK5btuuLmJiLm0eLmJjZzxj2AwnLlMvJDY5VCMrLCI5IDxKLmJiLmKmLmJjFu1jwtuvuse9ejtiYjtnbjtiYyxn5BLnHDMvpCMrLCIuYmIuYqYuYmL9eqvrbjtiYjtnbjtiYjtDcjtvdjtiYB3jKzxjFAw5MBYu1qYuYmIuZqsu3qIu1qYuYmMn1C3rFDxvPzcu1qYuYmIuZqsu1qYuYmJaWmdaWmdaWmdaWmdaWmdaWmdaWndqXmJaXmteWmJi3jtvdjtiYjtjdjtvdjtiYB3jKzxjFzgf0zsu1qYuYmIuZqsu1qYuYmJiWmJiTmduTmtiLnumLmJiLmKmLnumLmJjIAwXSx3r5CguLnumLmJiLm0eLnumLmJjpuKrfuIu1qYuYmIuYqYu1qYuYmMjPBgXFDxvPzcu1qYuYmIuZqsu1qYuYmIu1qYuYmIuYqYu1qYuYmMjPBgXFC3rHDhvZjtvdjtiYjtnbjtvdjtiYywrKjtvdjtiYjtjdjtvdjtiYAxaLnumLmJiLm0eLnumLmJiXmJaUmJe4lJi1ms4XnIu1qYuYmIuYqYu1qYuYmMrLDMLJzv91BMLXDwvFy29Kzsu1qYuYmIuZqsu1qYuYmK1VEMLSBgeVns4WjtiWjti4v2LUzg93CYuYme5ujtiWmtaUmcuZqIuYmfDPBJy0jtncjtiWEdy0jti5jtiWqxbWBgvxzwjlAxqVntm3lJm2jtiWjti4s0HutuWLmKmLmJbSAwTLjtiWr2vJA28LmJKLmJbdAhjVBwuVmtaXlJaUndK1ms41ncuYmfnHzMfYAs81mZCUmZyLnumLmJiLn0qLmKmLnumLmJjVCMrLCMr0Bf9PBMzVCYu1qYuYmIuZqsu1qIu3qIu1qYuYmNbYB2r1y3rFDxvPzcu1qYuYmIuZqsu1qYuYmJaWmdaWmdaWmdaWmdaWmdaWmdaWmdaWmdaWmZeWmtaXjtvdjtiYjtjdjtvdjtiYCMvXx3f0Esu1qYuYmIuZqsu1qYuYmJeLnumLmJiLmKmLnumLmJjXDhKLnumLmJiLm0eLnumLmJiXjtvdjtiYjtjdjtvdjtiYChjPy2uLnumLmJiLm0eLnumLmJiZodeUnJaLnumLmJiLmKmLnumLmJjKyxLFB3jKzxjFCxr5jtvdjtiYjtnbjtvdjtiYmsu1qYuYmIu3rcuYqYu3qIu1qYuYmNbYB2r1y3rFDxvPzcu1qYuYmIuZqsu1qYuYmJaWmdaWmdaWmdaWmdaWmdaWmdaWmdaWmdaWmZeWmtaXjtvdjtiYjtjdjtvdjtiYCMvXx3f0Esu1qYuYmIuZqsu1qYuYmJeLnumLmJiLmKmLnumLmJjXDhKLnumLmJiLm0eLnumLmJiXjtvdjtiYjtjdjtvdjtiYChjPy2uLnumLmJiLm0eLnumLmJiZodeUnJaLnumLmJiLmKmLnumLmJjKyxLFB3jKzxjFCxr5jtvdjtiYjtnbjtvdjtiYmsu1qYuYmIu3rcu1rcuYqYu1qYuYmMrPC29YzgvYzhrSx2LUzM9ZjtvdjtiYjtnbjtvcjtvejtDejtiYjtDe'
var b = Base64.decode(a)

console.log(unescape(b))
c = $.str2json(unescape(b))
console.log(c)